### PR TITLE
(Fix) Check that transaction data matches value in session

### LINKED ISSUE #168: (Bug) Can send multiple postcards to the same address
- **What is it?** (leave one option)
    * `(Bug)` report (i.e. something doesn't work as it should)

Malicious user calls `/prepareRegTx` endpoint `N` times, server generates `N` different confirmation codes and returns `N` different session keys `sk_1`, ..., `sk_N`. However, user only sends 1 tx to the contract, then uses this tx hash to send `N` calls to `/notifyRegTx` with different `sk_i`. This will result in server sending `N` postcards to the same address

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #168.

When a transaction is notified, check that the confirmation code hash in the transaction data matches the confirmation code in the given session. This avoids an attack where the same transaction is sent with different session keys and causes multiple postcards to be sent when only one payment was done.

### CODE REVIEW

File: web-dapp/controllers/notifyRegTx.js [hunk 1]
```diff
@@ -150,6 +151,16 @@ const removeUsedSessionKey = (opts, prelog) => {
         });
 };
 
+const validateTx = (txId, cc, sha3cc) => {
```
Comment (garatortiz) [inline web-dapp/controllers/notifyRegTx.js]: Where is `cc` used?

Comment (fvictorio) [reply web-dapp/controllers/notifyRegTx.js]: Fixed, thanks.

**Review by garatortiz — APPROVED** [review]

**Comment by phahulin** [comment]
@fvictorio please resolve conflicts

**Review by phahulin — APPROVED** [review]
